- hosts: all
  become: yes
  tasks:
    - name: Install dependencies for Docker repository
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker's official GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/trusted.gpg.d/docker.asc

    - name: Add Docker repository
      shell: echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    # Moved Docker login before pulling the image
    - name: Log in to Docker Hub
      docker_login:
        username: "containerguru1"
        password: "Madmithra!27"

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: containerguru1/sample-nodejs-app
        tag: latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: my_container
        image: containerguru1/sample-nodejs-app
        state: started
        restart_policy: always
        ports:
          - "81:80"  # Adjust the ports as needed
